/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emergentes;

import Conexion.Conexion;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Cris
 */
public class Buscador_informes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Buscador_informes
     */
    public Buscador_informes() {
        initComponents();
    }
    DefaultTableModel model;
    Connection conn;

    void mostrar() {
        String[] titulos = {"Id", "Nombre", "Apellido", "Fecha Nacimiento", "Telefono", "Correo", "Fecha de Registro", "Genero"};
        String[] registros = new String[8];

        String sql = "SELECT * FROM paciente";
        model = new DefaultTableModel(null, titulos);
        Conexion con = new Conexion();
        Connection cn = con.conectarMySQL();
        try {
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                //obtener el registro que queremos
                registros[0] = rs.getString("idpaciente");
                registros[1] = rs.getString("nombres");
                registros[2] = rs.getString("apellidos");
                registros[3] = rs.getString("fecha_nacimiento");
                registros[4] = rs.getString("telefono");
                registros[5] = rs.getString("correo");
                registros[6] = rs.getString("fecha_registro");
                registros[7] = rs.getString("sexo");
                model.addRow(registros);
            }
            table.setModel(model);
            model.fireTableDataChanged();
            rs.close();
            st.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.setFocusable(false);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 720, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            int index = table.getSelectedRow();
            TableModel mode = table.getModel();
            String id = (String) mode.getValueAt(index, 0);
            String nombre = (String) mode.getValueAt(index, 1);
            String apellido = (String) mode.getValueAt(index, 2);
            String telefono = (String) mode.getValueAt(index, 4);
            String correo = (String) mode.getValueAt(index, 5);
            //llamar a abrir el PDF QUE SE GENERO
            //modificar_paciente m = new modificar_paciente(id, nombre, apellido, telefono, correo);
           // m.setVisible(true);
        }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
